# Generated by Django 5.0.6 on 2024-06-15 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='comment_qty',
            new_name='comments_qty',
        ),
    ]
