# Generated by Django 5.0.6 on 2024-06-15 12:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_course_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория курсов', 'verbose_name_plural': 'Категории курсов'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Учебный курс', 'verbose_name_plural': 'Учебные курсы'},
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Дата и время создания', verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(help_text='Введите название категории', max_length=255, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(help_text='Выберите категорию курса', on_delete=django.db.models.deletion.CASCADE, related_name='course_category', to='shop.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='course',
            name='comments_qty',
            field=models.IntegerField(help_text='Введите количество комментариев для курса', verbose_name='Количество комментариев'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Дата и время создания', verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.FloatField(help_text='Введите цену курса', verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students_qty',
            field=models.IntegerField(help_text='Введите количество стедентов на курсе', verbose_name='Количество учащихся'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(help_text='Введите название курса', max_length=255, verbose_name='Курс'),
        ),
    ]
