# Generated by Django 5.0.6 on 2024-06-15 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_course_comments_qty_alter_course_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(help_text='Выберите категорию курса', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_category', to='shop.category', verbose_name='Категория'),
        ),
    ]
