# Generated by Django 5.0.6 on 2024-06-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_course_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('title',), 'verbose_name': 'Категория курсов', 'verbose_name_plural': 'Категории курсов'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('pk',), 'verbose_name': 'Учебный курс', 'verbose_name_plural': 'Учебные курсы'},
        ),
        migrations.AlterField(
            model_name='course',
            name='comments_qty',
            field=models.PositiveIntegerField(default=0, help_text='Введите количество комментариев для курса', verbose_name='Количество комментариев'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students_qty',
            field=models.PositiveIntegerField(default=0, help_text='Введите количество стедентов на курсе', verbose_name='Количество учащихся'),
        ),
    ]
